/*
 * @file lzvn_fullversion.h
 * Copyright 2018 René J.V. Bertin
 * This code is made available under the CPOL License
 * http://www.codeproject.com/info/cpol10.aspx
 */

#ifndef LZVN_FULLVERSION_H
#define LZVN_FULLVERSION_H

/* lzvn_fullversion.h.  Generated by cmake from lzvn_fullversion.h.cmake */

#define LZVN_FULL_VERSION_STRING "@lzvn_FULL_VERSION@"

#endif //  LZVN_FULLVERSION_H
